# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"    # Specify the package manager (Maven)
    directory: "/"                 # The directory containing the pom.xml (usually root)
    schedule:
      interval: "daily"           # Frequency of updates (can be "daily", "weekly", or "monthly")
    ignore:
      - dependency-name: "org.springframework.boot"
        versions: ["2.3.0", "2.3.1"]  # Example: Ignore specific versions of Spring Boot
  - package-ecosystem: "maven"
    directory: "/libs"             # Specify a subdirectory if your pom.xml is in a different folder
    schedule:
      interval: "weekly"

